### PR TITLE
Fix CI + docs

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by glwagner** [comment]
I think some PRs were merged without passing tests or docs? Is that right?

**Comment by navidcy** [comment]
Yes. Before this PR not even the `using ClimaOceanBiogeochemistry` was working. A comma was missing. This PR fixes this but still we meed to fix the tests.

**Comment by navidcy** [comment]
> I think some PRs were merged without passing tests or docs? Is that right?

I added a protection rule so that one of the CI is now required to merge.

**Comment by navidcy** [comment]
This PR is ready.

**Comment by navidcy** [comment]
@glwagner shall we merge this?

**Comment by navidcy** [comment]
Also the package is pinned on Oceananigans v0.81; is this intentional or should we bump up the compat entry to more recent versions of Oceananigans?

**Comment by glwagner** [comment]
We should bump the compat!

**Review by glwagner — APPROVED** [review]

**Pull request merged**
